In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest,chi2,RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier   
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier



In [2]:
dataset1=pd.read_csv("prep.csv",index_col=None)
df2=dataset1
df2 = pd.get_dummies(df2, drop_first=True)

indep_X=df2.drop('classification_yes', axis=1)
dep_Y=df2['classification_yes']

#sc=StandardScaler()

#indep_X_scaled=sc.fit_transform(indep_X)

#indep_X_scaled = pd.DataFrame(indep_X_scaled,columns=indep_X.columns)


In [14]:
log_model = LogisticRegression(solver='lbfgs',max_iter=20000)
RF = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
DT= DecisionTreeClassifier(criterion = 'gini', max_features='sqrt',splitter='best',random_state = 0)
svc_model = SVC(kernel = 'linear', random_state = 0)

rfelist=[]
rfemodellist=[log_model,svc_model,RF,DT]

In [15]:
#Takes a model (Logistic, SVM, RandomForest, etc.)
#Trains it on full features
#Finds feature importance (coef_ / feature_importances_)
#Removes least important features step-by-step
#Gives you BEST subset of features
# Output = selected features only


for i in rfemodellist:
    log_rfe=RFE(i, n_features_to_select=5, step=1)
    log_fit = log_rfe.fit(indep_X, dep_Y)
    log_rfe_feature=log_fit.transform(indep_X)
    rfelist.append(log_rfe_feature)

In [16]:
rfelist

[array([[3., 1., 0., 0., 0.],
        [2., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        ...,
        [3., 1., 0., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0.]], shape=(399, 5)),
 array([[3., 1., 0., 0., 1.],
        [2., 1., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        ...,
        [3., 1., 0., 1., 0.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]], shape=(399, 5)),
 array([[  3.        , 148.11267606,   3.07735602,  12.51815562,
          38.86890244],
        [  2.        , 148.11267606,   0.7       ,  10.7       ,
          34.        ],
        [  1.        ,  99.        ,   0.6       ,  12.        ,
          34.        ],
        ...,
        [  3.        , 110.        ,   6.        ,   9.1       ,
          26.        ],
        [  0.        , 207.        ,   6.8       ,   8.5       ,
          38.86890244],
        [  0.        , 100.        ,   1.        ,  16.3       ,
          53.        ]], shape=(399, 5)),
 array([[ 3.0

In [8]:
## Checking RFE after standardized the input

#sc=StandardScaler()
#indep_X_scaled=sc.fit_transform(indep_X)
#indep_X_scaled = pd.DataFrame(indep_X_scaled,columns=indep_X.columns)


In [9]:
#s_rfelist=[]
#rfemodellist=[log_model,svc_model,RF,DT]

In [10]:
#for i in rfemodellist:
#    log_rfe=RFE(i, n_features_to_select=5, step=1)
#    log_fit = log_rfe.fit(indep_X_scaled, dep_Y)
#    log_rfe_feature=log_fit.transform(indep_X_scaled)
#    s_rfelist.append(log_rfe_feature)

In [11]:
#s_rfelist

[array([[ 1.59943471e+00, -1.30982964e-15,  0.00000000e+00,
          1.93649167e+00, -7.19103794e-01],
        [ 8.37890020e-01, -6.70325374e-01, -5.97628025e-01,
          1.93649167e+00, -7.19103794e-01],
        [ 7.63453321e-02, -1.91035825e-01, -5.97628025e-01,
         -5.16397779e-01, -7.19103794e-01],
        ...,
        [ 1.59943471e+00, -1.26022020e+00, -1.57957915e+00,
          1.93649167e+00,  1.39061984e+00],
        [-6.85199355e-01, -1.48143076e+00,  0.00000000e+00,
         -5.16397779e-01,  1.39061984e+00],
        [-6.85199355e-01,  1.39430653e+00,  1.73450588e+00,
         -5.16397779e-01, -7.19103794e-01]], shape=(399, 5)),
 array([[ 1.59943471e+00,  7.90657760e-17, -1.30982964e-15,
          0.00000000e+00, -4.81125224e-01],
        [ 8.37890020e-01, -4.23265179e-01, -6.70325374e-01,
         -5.97628025e-01, -4.81125224e-01],
        [ 7.63453321e-02, -4.41069209e-01, -1.91035825e-01,
         -5.97628025e-01, -4.81125224e-01],
        ...,
        [ 1.59943471

In [19]:
X_train,X_test,y_train,y_test=train_test_split(indep_X,dep_Y , test_size=0.25 , random_state=0)
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [20]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
y_pred=classifier.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm = confusion_matrix(y_test, y_pred)
accuracy=accuracy_score(y_test, y_pred )
report=classification_report(y_test, y_pred)

In [23]:
accuracy

0.99